// try {
//     noExiste()
// } catch (error) {
//     console.log('hay un error ' + error);
// } finally{
//     console.log('finally');
// }







// try {
//     let num = 9
//     if (num !== 10){
//         throw new Error('lalalla')
//     }
// } catch (error) {
//     console.log('hay un error ' + error);
// } finally{
//     console.log('finally');
// }